global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# -"first.rules"
# -"second.rules"
scrape_configs:
  - job_name: spring-actuator
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.30.80.1:9090']